### ISSUE TITLE
Handling Dashboard - FIrst Page

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/Argos#138]
### Description

Create the first page of the handling dashboard with the 6 graphs shown on the mock. 

### Acceptance Criteria

- [ ] Looks like mocks
- [ ] Componentize the graph / use the already existing graph component
- [ ] Communicates with backend to query the necessary data either through the socket or http requests

### Proposed Solution

^

### Mocks

epic #137 
<img width="702" alt="Screenshot 2024-03-02 at 8 31 43 PM" src="https://github.com/Northeastern-Electric-Racing/Argos/assets/113635669/a69231c7-2ddd-4e65-8469-43cd1aa45dc6">

**Comment by RChandler234** [comment]
These need to be redone because of changes to the car, see #137 for the original plan and #256 for Spring Plans
