### ISSUE TITLE
Handling Dashboard - Create Second Page

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/Argos#139]
### Description

Similar to #138 create the second page of the handling dashboard with the associated 8 graphs

### Acceptance Criteria

- [ ] Looks like mock
- [ ] Linked with backend through both http requests and socket tracking
- [ ] Add necessary data points to identifier data type enumeration 

### Proposed Solution

^

### Mocks

epic #137 
<img width="692" alt="Screenshot 2024-03-02 at 8 35 32 PM" src="https://github.com/Northeastern-Electric-Racing/Argos/assets/113635669/250aa0a1-b9ed-40ab-aef3-d23aec9dcefd">

**Comment by RChandler234** [comment]
These need to be redone because of changes to the car, see #137 for the original plan and #256 for Spring Plans
