### ISSUE TITLE
Handling Dashboard - Create third page

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/Argos#140]
### Description

Similarly to #138 create the third page of the handling dashboard which is just two graphs 

### Acceptance Criteria

- [ ] Looks like mock
- [ ] uses graph component
- [ ] Only do the steering gauge and pushrod gauge not the xx force vs time graphs

### Proposed Solution

^

### Mocks

<img width="688" alt="Screenshot 2024-03-02 at 8 36 44 PM" src="https://github.com/Northeastern-Electric-Racing/Argos/assets/113635669/7ebe8868-ac18-4374-ab38-4cdd1dc77c70">

**Comment by RChandler234** [comment]
These need to be redone because of changes to the car, see #137 for the original plan and #256 for Spring Plans
