### ISSUE TITLE
[Client] - Reloading results in Nginx error

### ISSUE THREAD

**Issue by jr1221** [Northeastern-Electric-Racing/Argos#167]
### Observed Behavior

You cant reload the client using the browser reload, nor navigate to subpages.

### Expected Behavior

You can reload as needed to refresh data or try to fix small quirks.

### Steps to Reproduce

1. Reload
2. 
3.

**Comment by RChandler234** [comment]
From very quick googling, this is just something we need to configure and haven't, will look into

**Comment by RChandler234** [comment]
https://stackoverflow.com/questions/70735058/change-nginx-conf-file-inside-docker
