### ISSUE TITLE
Change - separator to / separator to match Calypso

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/Argos#175]
### Description

Been meaning to do this for a while, this is a reminder for myself to get it done

### Acceptance Criteria

Do it, clean up any related code

### Proposed Solution

Do it

### Mocks

N/A

**Comment by jr1221** [comment]
This would most likely involve a migration to DB as well right?  I dunno how its gonna work but it would be nice to convert DB to that by changing the dataTypeName  (ex. `Power-AC_Current` to `DTI/Power/AC_Current`) by doing node+dataTypeName replace all - with /.
 Also with this is there any reason to retain `Node`?

**Comment by RChandler234** [comment]
Yes definitely, that'll make this one significantly more involved. For the Node thing, there's not really a reason, but it'll require a pretty significant overhaul of the code

**Comment by jr1221** [comment]
Alright, feel free to lmk if you need any sort of help or want to task me to do this for scylla rust or whatever.  Im definitely clueless about the db implications tho. This will be a nice improvement:)
