### ISSUE TITLE
Add Relevant Mock Data to the Database

### ISSUE THREAD

**Issue by RChandler234** [Northeastern-Electric-Racing/Argos#176]
### Description

NOTE: Figure out what we're doing the Rust server before doing this

Right now, the mock data in the database doesn't all line up with the data types we have stored in the client/ scylla. This ticket is to add a bunch more mock data so it's easier to simulate functionality on places like the graph page

### Acceptance Criteria

A bunch of mock data has been added

### Proposed Solution

Add it pls

### Mocks

N/A

**Comment by jr1221** [comment]
Making this work off the YAML would be super cool, but prob overkill lol.  Would also make it depend on #175
