### ISSUE TITLE
[Client] - Setup Automatical Formatting and Linting Before Each Commit

### ISSUE THREAD

**Issue by Char2sGu** [Northeastern-Electric-Racing/Argos#187]
### Desired Changes

Possible with package `husky` and `lint-staged`

**Comment by RChandler234** [comment]
make prettier scoped just to this project, have a script for prettier formatting and a script for eslint formatting

**Comment by RChandler234** [comment]
we want to do a pre-commit hook that errors if prettier/ linter fails instead of auto-changing the code/ failing build
