### ISSUE TITLE
[Client] - Grid Aligned Dashboard

### ISSUE THREAD

**Issue by Char2sGu** [Northeastern-Electric-Racing/Argos#196]
### Current Features

![image](https://github.com/user-attachments/assets/ccc33335-5e0a-4571-b607-b5f2dd681a35)
There's no visual balance. The paddings are not consistent, and the alignment are also weird

### Desired Additional Features

Grid-based layout for dashboard widgets, and consistent paddings for widgets.

**Comment by Char2sGu** [comment]
Additionally, when scrolled to the bottom of the main dashboard, there is no padding at the bottom, which looks weird.
![image](https://github.com/user-attachments/assets/8b40d679-7a91-4872-a1e4-d6311e035dc5)

**Comment by RChandler234** [comment]
Other tickets for this already
