### ISSUE TITLE
[Client] - Switching Data Source via Dependency Injection

### ISSUE THREAD

**Issue by Char2sGu** [Northeastern-Electric-Racing/Argos#197]
### Current Features

There's no data available for development. Several errors reported in console.
![image](https://github.com/user-attachments/assets/36fe2b36-9d97-4ca7-a8f2-f48039809dd4)

### Desired Additional Features

Leveraging Angular's DI system, we can have two different implementations of the data fetching services, and provide them in two modules:

- RealDataModule
- MockDataModule

The different implementations are provided in the corresponding modules, and we can switch from these two data sources by importing different modules. When combined with the `environment.ts` file, it is possible to automatically switch to production data  for production build, and use mock data for development by default.

Example: https://github.com/Char2sGu/reply/tree/develop/projects/reply/src/backends

**Comment by RChandler234** [comment]
Shouldn't need this anymore as we have the mock calypso now
