### ISSUE TITLE
[Client] - Header re-design home page

### ISSUE THREAD

**Issue by bracyw** [Northeastern-Electric-Racing/Argos#212]
### Description

We have a draft for a new header for the home page. This ticket is for re-designing it based on that mock.

### Acceptance Criteria

Looks like the mock below.

### Proposed Solution

1. make a new header component, under the src/pages/landing-page in a new folder landing-page-header
2. put - (big time title typography), date and location typography, latency-display component, connection component - into ur new header component
3. Then resizie landing page to fit new design

### Mocks

![new top bar home screen mock](https://github.com/user-attachments/assets/1cbb9986-5c50-4ac6-af2a-adf53d2ea8c0)

**Comment by justinsoto** [comment]
Update

New Component Layout: Time, Location, Connection, Viewers, Current Run
