### ISSUE TITLE
Angular Client - Create Better No Data Selected Screen

### ISSUE THREAD

**Issue by Peyton-McKee** [Northeastern-Electric-Racing/Argos#82]
### Description

When the router isnt connected to the car, there wont be any realtime data to be displayed, so when a user clicks more details they wont be able to see any data create a pop up / toast that is displayed instead of displaying the current no data screen 

### Acceptance Criteria

- [ ] Pop up / toast component to display when something bad happens in the app
- [ ] Displays this toast component when not connected to the router 

### Proposed Solution

https://primeng.org/toast

**Comment by Amenawon** [comment]
Hey! can i be assigned this task?

**Comment by Peyton-McKee** [comment]
unfortunately only members of Northeastern Electric Racing can contribute to this repository.
